In [4]:
import xarray as xr

# Open the dataset
ds = xr.open_dataset("..\data\era5_cache\era5_2015_11.nc")

# Print the readable summary of variables and coordinates
print(ds)

<>:4: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:4: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\Sumithra\AppData\Local\Temp\ipykernel_16664\1257641501.py:4: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  ds = xr.open_dataset("..\data\era5_cache\era5_2015_11.nc")

<xarray.Dataset> Size: 936B
Dimensions:     (valid_time: 4, latitude: 4, longitude: 4)
Coordinates:
  * valid_time  (valid_time) datetime64[ns] 32B 2015-11-29T09:00:00 ... 2015-...
    expver      (valid_time) <U4 64B ...
  * latitude    (latitude) float64 32B 16.5 16.25 16.0 15.75
  * longitude   (longitude) float64 32B -87.25 -87.0 -86.75 -86.5
    number      int64 8B ...
Data variables:
    u10         (valid_time, latitude, longitude) float32 256B ...
    v10         (valid_time, latitude, longitude) float32 256B ...
    sst         (valid_time, latitude, longitude) float32 256B ...
Attributes:
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-09-07T18:14 GRIB to CDM+CF via cfgrib-0.9.1...

In [7]:
import cdsapi

dataset = "reanalysis-era5-single-levels"
request = {
    "product_type": ["reanalysis"],
    "variable": [
        "10m_u_component_of_wind",
        "10m_v_component_of_wind",
        "sea_surface_temperature"
    ],
    "year": ["2019"],
    "month": ["12"],
    "day": ["01"],
    "time": ["03:00"],
    "data_format": "netcdf",              # CHANGED from "grib"
    "download_format": "unarchived",
    "area": [-5.75, 106.75, -6, 107]
}

client = cdsapi.Client()
client.retrieve(dataset, request).download("era5_data.nc") # CHANGED to .nc
print("Download complete!")

2026-09-08 00:36:11,585 INFO Request ID is 519b62a8-7da9-470f-8106-a09275b34fff
2026-09-08 00:36:12,001 INFO status has been updated to accepted
2026-09-08 00:36:35,084 INFO status has been updated to running
2026-09-08 00:36:46,860 INFO status has been updated to successful

f82a081e78db2b86a50cb0e81e0955d1.nc:   0%|          | 0.00/41.9k [00:00<?, ?B/s]

Download complete!

In [8]:
import xarray as xr
import numpy as np

# Open the NetCDF file (xarray will automatically use the installed netcdf4 engine)
ds = xr.open_dataset("era5_data.nc")

# Calculate total wind speed
ds['wind_speed'] = np.sqrt(ds.u10**2 + ds.v10**2)

# Convert to pandas DataFrame and drop NaNs
df = ds.to_dataframe().reset_index().dropna()

# Display the tabular data
display(df[['latitude', 'longitude', 'u10', 'v10', 'wind_speed', 'sst']])

   latitude  longitude       u10       v10  wind_speed         sst
0     -5.75     106.75 -2.589401 -0.299866    2.606706  303.257812
1     -5.75     107.00 -2.921432  0.469666    2.958945  303.330078
2     -6.00     106.75 -2.443893 -0.602600    2.517090  303.383789
3     -6.00     107.00 -2.684128 -0.103577    2.686126  303.417969

In [10]:
import xarray as xr
import numpy as np

# Open the NetCDF file (xarray will automatically use the installed netcdf4 engine)
ds = xr.open_dataset("..\data\era5_cache\era5_2015_11.nc")

# Convert to pandas DataFrame and drop NaNs
df = ds.to_dataframe().reset_index().dropna()

# Display the tabular data
display(df)

<>:5: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<>:5: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
C:\Users\Sumithra\AppData\Local\Temp\ipykernel_16664\119964322.py:5: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
  ds = xr.open_dataset("..\data\era5_cache\era5_2015_11.nc")

,valid_time,latitude,longitude,u10,v10,sst,number,expver
0,2015-11-29 09:00:00,16.50,-87.25,-5.101471,-4.326096,301.691895,0,0001
1,2015-11-29 09:00:00,16.50,-87.00,-5.072174,-4.499924,301.667480,0,0001
2,2015-11-29 09:00:00,16.50,-86.75,-5.113190,-4.853439,301.702637,0,0001
3,2015-11-29 09:00:00,16.50,-86.50,-4.997955,-5.112228,301.782715,0,0001
4,2015-11-29 09:00:00,16.25,-87.25,-5.354401,-3.052658,301.702637,0,0001
5,2015-11-29 09:00:00,16.25,-87.00,-4.951080,-2.932541,302.013184,0,0001
6,2015-11-29 09:00:00,16.25,-86.75,-4.867096,-3.200119,302.014160,0,0001
7,2015-11-29 09:00:00,16.25,-86.50,-4.615143,-3.434494,301.792480,0,0001
8,2015-11-29 09:00:00,16.00,-87.25,-4.992096,-1.528244,301.756348,0,0001
9,2015-11-29 09:00:00,16.00,-87.00,-4.324127,-1.246994,301.754395,0,0001
10,2015-11-29 09:00:00,16.00,-86.75,-2.527252,-0.463791,301.599121,0,0001
11,2015-11-29 09:00:00,16.00,-86.50,-2.244049,-0.681564,301.393066,0,0001
12,2015-11-29 09:00:00,15.75,-87.25,-2.617096,-0.205002,301.837402,0,0001
14,2015-11-29 09:00:00,15.75,-86.75,-0.489166,0.769608,301.151855,0,0001
15,2015-11-29 09:00:00,15.75,-86.50,0.187592,1.139725,301.151855,0,0001
16,2015-11-29 10:00:00,16.50,-87.25,-5.068726,-4.394531,301.691895,0,0001
17,2015-11-29 10:00:00,16.50,-87.00,-5.004272,-4.531250,301.667480,0,0001
18,2015-11-29 10:00:00,16.50,-86.75,-4.999390,-4.804688,301.702637,0,0001
19,2015-11-29 10:00:00,16.50,-86.50,-4.911499,-4.989258,301.782715,0,0001
20,2015-11-29 10:00:00,16.25,-87.25,-5.212280,-3.041992,301.702637,0,0001
21,2015-11-29 10:00:00,16.25,-87.00,-4.920288,-2.739258,302.013184,0,0001
22,2015-11-29 10:00:00,16.25,-86.75,-4.871460,-2.865234,302.014160,0,0001
23,2015-11-29 10:00:00,16.25,-86.50,-4.692749,-2.905273,301.792480,0,0001
24,2015-11-29 10:00:00,16.00,-87.25,-4.829468,-1.515625,301.756348,0,0001
25,2015-11-29 10:00:00,16.00,-87.00,-4.356812,-1.076172,301.754395,0,0001
26,2015-11-29 10:00:00,16.00,-86.75,-2.897827,-0.003906,301.599121,0,0001
27,2015-11-29 10:00:00,16.00,-86.50,-2.681030,-0.023438,301.393066,0,0001
28,2015-11-29 10:00:00,15.75,-87.25,-2.536499,-0.060547,301.837402,0,0001
30,2015-11-29 10:00:00,15.75,-86.75,-0.848999,1.100586,301.151855,0,0001
31,2015-11-29 10:00:00,15.75,-86.50,-0.228882,1.392578,301.151855,0,0001
32,2015-11-29 11:00:00,16.50,-87.25,-4.845001,-4.285812,301.691895,0,0001
33,2015-11-29 11:00:00,16.50,-87.00,-4.867462,-4.365891,301.667480,0,0001
34,2015-11-29 11:00:00,16.50,-86.75,-4.950470,-4.576828,301.702637,0,0001
35,2015-11-29 11:00:00,16.50,-86.50,-4.885040,-4.755539,301.782715,0,0001
36,2015-11-29 11:00:00,16.25,-87.25,-4.984650,-3.102219,301.702637,0,0001
37,2015-11-29 11:00:00,16.25,-87.00,-4.810822,-2.566086,302.013184,0,0001
38,2015-11-29 11:00:00,16.25,-86.75,-4.811798,-2.661789,302.014160,0,0001
39,2015-11-29 11:00:00,16.25,-86.50,-4.584259,-2.861008,301.792480,0,0001
40,2015-11-29 11:00:00,16.00,-87.25,-4.552032,-1.678391,301.756348,0,0001
41,2015-11-29 11:00:00,16.00,-87.00,-4.227814,-1.068039,301.754395,0,0001
42,2015-11-29 11:00:00,16.00,-86.75,-2.804962,-0.065109,301.599121,0,0001
43,2015-11-29 11:00:00,16.00,-86.50,-2.540314,-0.241867,301.393066,0,0001
44,2015-11-29 11:00:00,15.75,-87.25,-2.408478,-0.134445,301.837402,0,0001
46,2015-11-29 11:00:00,15.75,-86.75,-0.803009,0.895828,301.151855,0,0001
47,2015-11-29 11:00:00,15.75,-86.50,-0.212189,1.211258,301.151855,0,0001
48,2015-11-29 12:00:00,16.50,-87.25,-4.846161,-4.214432,301.691895,0,0001
49,2015-11-29 12:00:00,16.50,-87.00,-4.949677,-4.231033,301.667480,0,0001
50,2015-11-29 12:00:00,16.50,-86.75,-5.065887,-4.366776,301.702637,0,0001
51,2015-11-29 12:00:00,16.50,-86.50,-5.014130,-4.596268,301.782715,0,0001
52,2015-11-29 12:00:00,16.25,-87.25,-5.096161,-3.096268,301.702637,0,0001
53,2015-11-29 12:00:00,16.25,-87.00,-4.971161,-2.481033,302.013184,0,0001
54,2015-11-29 12:00:00,16.25,-86.75,-4.929169,-2.511307,302.014160,0,0001
55,2015-11-29 12:00:00,16.25,-86.50,-4.567841,-2.787674,301.792480,0,0001
56,2015-11-29 12:00:00,16.00,-87.25,-4.637177,-1.643143,301.756348,0,0001
57,2015-11-29 12:00:00,16.00,-87.00,-4.357880,-1.024002,301.754395,0,0001
58,2015-11-29 12:00:00,16.00,-86.75,-2.718231,-0.247635,301.599121,0,0001
59,2015-11-29 12:00:00,16.00,-86.50,-2.321747,-0.505447,301.393066,0,0001
60,2015-11-29 12:00:00,15.75,-87.25,-2.436005,-0.078690,301.837402,0,0001
62,2015-11-29 12:00:00,15.75,-86.75,-0.644012,0.691818,301.151855,0,0001
63,2015-11-29 12:00:00,15.75,-86.50,-0.074677,1.006271,301.151855,0,0001